name: Unbx Code Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unbx Code Scan
        uses: unbx-dev/unbx-cli@v0.0.10
        with:
          access_token: ${{ secrets.UNBX_ACCESS_TOKEN }}
          secret_token: ${{ secrets.UNBX_SECRET_TOKEN }}
          repository_id: ${{ github.repository_id }}
          repository: ${{ github.repository }}
          sha: ${{ github.event.pull_request.head.sha }}
          pr_number: ${{ github.event.pull_request.number }}
